.PHONY: clean All

All:
	@echo "----------Building project:[ jorn - Debug ]----------"
	@cd "jorn" && "$(MAKE)" -f  "jorn.mk"
clean:
	@echo "----------Cleaning project:[ jorn - Debug ]----------"
	@cd "jorn" && "$(MAKE)" -f  "jorn.mk" clean
