#############################################################################
# 
# dummy Makefile for bmptk hwcpp/chips directory
#
# (c) Wouter van Ooijen (www.voti.nl) 2012, 2013
# 
#############################################################################

.PHONY: clean build run error

clean: error
build: error
run: error

MSG  = You are trying to build in a library directory.
MSG += Make one of the project source files your current editor file.

error:
	$(error $(MSG) )
		
		