#############################################################################
#
# file : Makefile
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################d

# source files in this project (main.cpp is automatically assumed)
SOURCES            +=

# header files in this project
HEADERS            += 

# other places to look for files for this project
SEARCH             += 

# extra results that must be built
RESULTS            += main.lst main.lss

# set RELATIVE to the next higher directory and defer to the makefile.link
RELATIVE           := ../
include            $(RELATIVE)Makefile.link
